nfeats: 263
latent_dim: [7,256]
ff_size: 1024
num_layers: 9
num_heads: 4
dropout: 0.1
arch: encoder_decoder
normalize_before: False
activation: gelu
position_embedding: learned
device: cuda
keyframe_freq: 0.1
max_motion_len: 196
keyframes_only: True
beta0: 0.0001



CHECKPOINTS: ./checkpoints/mldvaev7_bs32_b0-4_encdec.pth
LOG:
  path: ./log/mldvaev7_bs32_b0-4encdec.log

TRAIN:
  EPOCHS: 500
  lr: 0.00001
  device: cuda

DATALOADER:
  NAME: humanml
  batch_size: 100