EVALUATORWRAPPER:
  dataset_name: humanml
  device: cuda
  dim_word: 300
  max_motion_length: 196
  dim_pos_ohot: 15
  dim_motion_hidden: 1024
  max_text_len: 20
  dim_text_hidden: 512
  dim_coemb_hidden: 512
  dim_pose: 263 # if dataset_name == 'humanml' else 251
  dim_movement_enc_hidden: 512
  dim_movement_latent: 512
  checkpointsdir: './pretraining/'
  unit_length: 4